complete/blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

#app_name='blog'
urlpatterns = [
    path('show/<int:pk>/', views.index, name='blog_index'),
    #url(r'^show/(?P<pk>\d+)/$',views.index,name='blog_index'),
    path('post/<int:pk>/', views.details, name='details'),
    path('post/new/<int:pk>/', views.newpost, name='newpost'),
    path('post/<int:pk>/edit', views.editpost, name='editpost'),
    path('post/<int:pk>/delete', views.deletepost, name='deletepost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.addcomment, name='add-comment'),
]

complete/complete/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from accounts.views import home
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from chat.views import index

from put_calendar.api.router import router

from put_calendar.views import *


from rest_framework.authtoken import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('assignments/', include('assignments.urls')),
    url('notifications/', include('notifications.urls')),
    url('clients/', include('clients.urls')),
    url('accounts/',include('accounts.urls')),
    url('history/', include('history.urls')),
    url('^$',home),
    url('blog/', include('blog.urls')),
    url('calendar/',include('put_calendar.urls')),
    url('chat/',include('chat.urls')),
    url('api/posts/',include('blog.api.urls')),
    path('api/',include(router.urls)),
    path('api-token-auth/',views.obtain_auth_token,name='api-token-auth'),


    url(r'^api/dates/$', DatesListView.as_view()),
    url(r'^api/dates/(?P<pk>\d+)/$', DatesView.as_view()),
    url(r'^api/user/$', UserListView.as_view()),
    url(r'^api/user/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^api/filter/(?P<pk>\d+)/$', DatesFilterView.as_view()),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complete/put_calendar/urls.py
from django.urls import path
from put_calendar import views
from django.conf.urls import url
app_name='put_calendar'
urlpatterns = [






    url(r'^next/(?P<select>\w+)/(?P<show>\w+)/$', views.date, name='date'),
    #path('next/<select>/',views.date,name = "date"),
    #path('back/<select>/',views.date1,name = "date1"),
    url(r'^back/(?P<select>\w+)/(?P<show>\w+)/$', views.date1, name='date1'),
    path('events_enter/<int:date_selected>',views.event_enter,name="event_enter"),
    url(r'^land/(?P<select>\w+)/(?P<show>\w+)/$', views.hello, name='index'),
	url(r'^choose/(?P<select>\w+)/(?P<show>\w+)/$', views.choose_event, name='choose'),


]

complete/templates/put_templates/date.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

    <link rel="stylesheet" href="{% static 'css/date.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

</head>
<body>
<div class="container">

    <div class="jumbotron" style="display:flex">

            {% if form  %}
            <div style="flex: 0 0 25%;background-color: #a700ff;">
                &nbsp;
                <p>{{final_date}}<p>
                    <p><p>
                <p> Events:<p>
                {% for i in events %}
                <p> {{i.work_title}} </p>
                {% endfor %}
                <br>
                <br>
                <br>
                <div class="container">
                    <form method="post">
                        {% csrf_token %}

                        <p>Add a event on this day:
                            <br>
                            {{form.work_title}}<p>

                    <button type="submit">Create Event</button>
                    </form>
                 </div>
                 <div>

                    <form action="{% url 'put_calendar:choose' select='1' show='1'%}" method="post" >
                        {% csrf_token %}

                        {{mandy.as_p}}

                    <input type="submit" value="Go" class="btn btn-dark">
                </form>

                </div>

            </div>
             {% else %}

             <div style="flex: 0 0 25%;background-color: yellow;">
                &nbsp;
                 <div>
                    <form action="{% url 'put_calendar:choose' select='1' show='1'%}" method="post">
                        {% csrf_token %}

                        {{mandy.as_p}}

                    <input type="submit" value="Go" class="btn btn-dark">
                </form>
                </div>
             </div>



             {% endif %}
        <center style="flex: 1">

            <main>

                <form action="{% url 'put_calendar:date' select='1' show='1'%}" method="post" style="position : relative;float : right;">
                    {% csrf_token %}
                    <input type="submit" value="next" class="btn btn-dark">
                </form>

                <form action="{% url 'put_calendar:date1' select='1' show='1' %}" method="post" style="position : relative;float:left;">
                    {% csrf_token %}
                    <input type="submit" value="back" class="btn btn-dark">
                </form>

                <h3>CALENDAR</h3>

                <div class="calendar">
                    <p>{{ present_year }}</p>
                    <div class="calendar__header">
                        <div>mon</div>
                        <div>tue</div>
                        <div>wed</div>
                        <div>thu</div>
                        <div>fri</div>
                        <div>sat</div>
                        <div>sun</div>
                    </div>


                    {% for i,j in zipped_data %}

                        <div class="calendar__week">
                            {% if i.0 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no  show=i.0 %}'" >{{ i.0 }}</button>

                            {% endif %}


                            {% if i.1 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no show=i.1 %}'" >{{ i.1 }}</button>

                            {% endif %}


                            {% if i.2 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no show=i.2 %}'" >{{ i.2 }}</button>

                            {% endif %}

                            {% if i.3 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no show=i.3 %}'" >{{ i.3 }}</button>

                            {% endif %}


                            {% if i.4 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no show=i.4 %}'" >{{ i.4 }}</button>

                            {% endif %}

                            {% if i.5 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no show=i.5 %}'" >{{ i.5 }}</button>

                            {% endif %}


                            {% if i.6 == 0 %}
                                <div class="calendar__day day" data-toggle="modal" data-target="#myModal"></div>
                            {% else %}
                                <button type="button" class="btn btn-primary" onclick="location.href='{% url 'put_calendar:index' select=year_no show=i.6 %}'" >{{ i.6 }}</button>

                            {% endif %}

                        </div>
                    {% endfor %}
                </div>

            </main>

        </center>
    </div>

</div>

</body>
</html>

complete/templates/put_templates/events_create.html
{% extends "homepage.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h3 class="mt-2">Add Event</h3>
          <hr class="mt-0 mb-4">

  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
      <br>
    <button type="submit" class="btn btn-success">Add Event</button>
  </form>
        </div>
      </div>



</div>

{% endblock %}