complete/assignments/urls.py
from django.conf.urls import url
from . import views

app_name = 'assignments'




urlpatterns = [
    #assignments


    #assignments/display
    url('display/$',views.display_view, name='display'),

    #assignments/my_todo
    url('my_todo/$',views.my_todo_view, name='my_todo'),

    #assignments/display/delete
    url('display/delete/(?P<task_id>[0-9]+)',views.delete_tasks,name='delete_task'),

    # assignments/display/update
    url('display/update/(?P<task_id>[0-9]+)', views.update_tasks, name='update_task'),

    #assignments/my_todo/add
    url('my_todo/add/', views.add_todo_list_view, name='add_todo'),

    url('my_todo/delete/(?P<todo_id>[0-9]+)', views.delete_todo, name='delete_todo'),

    url('my_todo/update/(?P<todo_id>[0-9]+)', views.update_todo, name='update_todo'),

]

complete/blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

#app_name='blog'
urlpatterns = [
    path('show/<int:pk>/', views.index, name='blog_index'),
    #url(r'^show/(?P<pk>\d+)/$',views.index,name='blog_index'),
    path('post/<int:pk>/', views.details, name='details'),
    path('post/new/<int:pk>/', views.newpost, name='newpost'),
    path('post/<int:pk>/edit', views.editpost, name='editpost'),
    path('post/<int:pk>/delete', views.deletepost, name='deletepost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.addcomment, name='add-comment'),
]

complete/complete/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from accounts.views import home
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from chat.views import index

from put_calendar.api.router import router

from put_calendar.views import *


from rest_framework.authtoken import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('assignments/', include('assignments.urls')),
    url('notifications/', include('notifications.urls')),
    url('clients/', include('clients.urls')),
    url('accounts/',include('accounts.urls')),
    url('history/', include('history.urls')),
    url('^$',home),
    url('blog/', include('blog.urls')),
    url('calendar/',include('put_calendar.urls')),
    url('chat/',include('chat.urls')),
    url('api/posts/',include('blog.api.urls')),
    path('api/',include(router.urls)),
    path('api-token-auth/',views.obtain_auth_token,name='api-token-auth'),


    url(r'^api/dates/$', DatesListView.as_view()),
    url(r'^api/dates/(?P<pk>\d+)/$', DatesView.as_view()),
    url(r'^api/user/$', UserListView.as_view()),
    url(r'^api/user/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^api/filter/(?P<pk>\d+)/$', DatesFilterView.as_view()),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complete/assignments/models.py
from django.db import models
from django.utils import timezone
from accounts.models import *
from django.contrib.auth.models import User
from notifications.models import *
from django.dispatch import receiver
from django.db.models.signals import post_save
from put_calendar.models import check_date
from history.models import recent_activity
from datetime import datetime
from django.utils import timezone

# Create your models here.
class TaskList(models.Model):
    title = models.CharField(max_length=250)
    project_name = models.CharField(max_length=250)
    description = models.TextField(blank=True,null=True)
    created = models.DateField()
    due_date = models.DateField()
    time_of_submission = models.DateField(blank=True,null=True)
    done = models.BooleanField(default=False)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    work = models.ForeignKey(Todolist,on_delete=models.CASCADE)


    class Meta:
        ordering = ['created']
        unique_together = ['title', 'project_name',]

class MyTodoList(models.Model):
    title = models.CharField(max_length=250)
    due_date =models.DateField()
    done = models.BooleanField(default=False)
    user = models.ForeignKey(User,on_delete=models.CASCADE)


    class Meta:
        unique_together = ['title','due_date',]



@receiver(post_save, sender=MyTodoList)
def add_to_other(sender, instance,created,updated_fields='done', **kwargs):
    if created:
        NotificationList.objects.create(message=instance.title+'added in todo list',user=instance.user)
    elif updated_fields is 'done':
        NotificationList.objects.create(message=instance.title+'marked done',user=instance.user)


@receiver(post_save, sender=TaskList)
def add_to_another(sender, instance,created,updated_fields='done', **kwargs):
    if created:
        pass
    elif updated_fields is 'done':
        NotificationList.objects.create(message=instance.title+'marked done',user=instance.user)
        upstatus=Todolist.objects.filter(pk=instance.work.pk)
        upstatus.update(status=instance.done)
        '''upnotify=to_notify.objects.filter(work=instance.work)
        upnotify.update(done=instance.done)'''

@receiver(post_save,sender=work_assigned)
def assign_task(sender,instance,created,**kwargs):
    if created:
        qwe=Todolist.objects.get(pk=instance.work.pk)
        print(qwe)
        w=work_assigned.objects.get(pk=instance.pk)
        print(w.user_assign)
        NotificationList.objects.create(message=instance.work.title+'added in tasklist',user=instance.user_assign)
        print(w)
        TaskList.objects.create(
            title=instance.work.title,
            project_name=instance.work.project_name,
            description=instance.work.description,
            created=instance.work.assigned,
            due_date=instance.work.deadline,
            done=instance.work.status,
            user=instance.user_assign,
            work = qwe
        )


@receiver(post_save,sender=to_notify)
def notify_done(sender,instance,created,updated_fields='done',**kwargs):
    if created:
        NotificationList.objects.create(message='you assigned a new task',user=instance.user_notify)
    elif updated_fields is 'done':
        NotificationList.objects.create(message='task you assigned is done',user=instance.user_notify)


@receiver(post_save,sender=TaskList)
def add_to_cal(sender,instance,created,**kwargs):
    if created:
        check_date.objects.create(
            work_title=instance.title,
            date=instance.due_date,
            user=instance.user
        )

@receiver(post_save,sender=MyTodoList)
def add_todo_to_cal(sender,instance,created,**kwargs):
    if created:
        check_date.objects.create(
            work_title=instance.title,
            date=instance.due_date,
            user=instance.user
        )

@receiver(post_save,sender=MyTodoList)
def add_todo_history(sender,instance,created,updated_fields='done',**kwargs):
    if updated_fields is 'done':
        recent_activity.objects.create(
            task_done=instance.title,
            dates=timezone.now().date(),
            times=timezone.now().time(),
            user=instance.user,

        )

@receiver(post_save,sender=TaskList)
def add_todo_history(sender,instance,created,updated_fields='done',**kwargs):
    if updated_fields is 'done':
        recent_activity.objects.create(
            task_done=instance.title,
            dates=timezone.now().date(),
            times=timezone.now().time(),
            user=instance.user,

        )

complete/assignments/forms.py
from django import forms

from .models import MyTodoList

class MyTodoform(forms.ModelForm):
    class Meta:
        model = MyTodoList
        fields =[
            'title', 'due_date'
        ]

complete/assignments/views.py
from django.shortcuts import render, redirect
from .models import TaskList, MyTodoList
from django.utils import timezone
from .forms import MyTodoform

from django.contrib import messages
from history.models import recent_activity
from datetime import datetime
from django.utils import timezone
from notifications.models import NotificationList
from accounts.models import *

# Create your views here.

def display_view(request):
    all_tasks = TaskList.objects.filter(user=request.user)
    all_tasks.order_by('-created').reverse()
    rev_all_tasks = list(reversed(all_tasks))
    return render(request, 'assignments/display.html', {'all_tasks':rev_all_tasks})

def my_todo_view(request):
    all_todo = MyTodoList.objects.filter(user=request.user)
    all_todo.reverse()
    rev_all_todo = list(reversed(all_todo))
    return render(request, 'assignments/my_todo.html',{'all_todo':rev_all_todo})

def delete_tasks(request,task_id):
    item = TaskList.objects.get(pk = task_id)
    item.delete()
    return redirect('assignments:display')

def update_tasks(request,task_id):
    item = TaskList.objects.get(pk = task_id)
    item.done = True
    item.time_of_submission = timezone.now()

    notify = to_notify.objects.get(work=item.work)

    if item.due_date >= item.time_of_submission.date():
        message= 'the task you assigned to  '+str(item.user.username)+ ' has completed the task  on time '+str(item.time_of_submission.date())+' successfully.'
        NotificationList.objects.create(message=message,user=notify.user_notify)
    elif item.due_date < item.time_of_submission.date():
        message= 'the task you assigned to  '+str(item.user.username)+ ' has completed the task late on '+str(item.time_of_submission.date())+' successfully.'
        NotificationList.objects.create(message=message,user=notify.user_notify)


    item.save()
    return redirect('assignments:display')


def add_todo_list_view(request):
    form =MyTodoform(request.POST or None)
    if form.is_valid():
        forminstance=form.save(commit=False)
        forminstance.user=request.user
        forminstance.save()
        return redirect('assignments:my_todo')
    context ={'form':form}
    return render(request,'assignments/add_todo.html' ,context)

def delete_todo(request,todo_id):
    item = MyTodoList.objects.get(pk = todo_id)
    item.delete()
    return redirect('assignments:my_todo')


def update_todo(request,todo_id):
    item = MyTodoList.objects.get(pk = todo_id)
    item.done = True
    recent_activity.objects.create(
            task_done=item.title,
            dates=timezone.now().date(),
            times=timezone.now().time(),
            user=request.user,

        )
    item.save()
    return redirect('assignments:my_todo')

complete/assignments/templates/assignments/add_todo.html
{% extends "homepage.html" %}
{% block content1 %}
{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
              <div class="card">
                <div class="card-body">
                <h3 class="mt-2">Add Todo</h3>
                <hr class="mt-0 mb-4">

                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <button type="submit" class="btn btn-success">add todo</button>
                </form>
              </div>
            </div>
        </div>



    </div>
  </div>


{% endblock %}

complete/assignments/templates/assignments/display.html
{% extends 'homepage.html' %}

{% block content %}


    <center>
        <h3 class="display-4" style="font-size:40px;color:white;font-weight:400;">My Assignments</h3><hr>
    </center>
    <div class="container" style="border-radius: 20px;padding: 25px;">


        <table class="table table-striped">
            <thead class="thead-light">
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Project Name</th>
                <th scope="col">Due Date</th>
                <th scope="col">Time of Submission</th>
                <th scope="col"></th>

            </tr>
            </thead>
            <tbody>
            {% for task in all_tasks %}
                <tr style="background-color:white">
                    {% if task.done == False %}

                        <th scope="row" style="font-weight: 600">
                            <i class="fa fa-circle" style="color: red"></i>&nbsp; {{ task.title }}</th>
                    {% elif task.done %}
                        <th scope="row" style="font-weight: 600">
                            <i class="fa fa-circle" style="color: green"></i>&nbsp;{{ task.title }}</th>
                    {% endif %}


                    <td>{{ task.project_name }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>{{ task.time_of_submission }}</td>


                    {% if task.done == False %}

                        <td><a class="btn btn-primary" href="{% url 'assignments:update_task' task.id %}" role="button">
                            <i class="fa fa-edit"></i>Done</a></td>
                    {% elif task.done %}
                        <td><a class="btn btn-primary" href="{% url 'assignments:delete_task' task.id %}" role="button">
                            <i class="fa fa-trash"></i>delete</a></td>
                    {% endif %}

                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
{% endblock %}

complete/assignments/templates/assignments/my_todo.html
{% extends 'homepage.html' %}

{% block content %}


    <center xmlns="http://www.w3.org/1999/html">
        <h3 class="display-4" style="color:white;">My To dos</h3>
        <a style="alignment-baseline: after-edge;" href="{% url 'assignments:add_todo' %}" role="button">
            <button type="button" class="btn btn-primary" style="background-color: #6d7fcc;">Add Todo <i class="fa fa-edit"></i></button>

        </a>
        </a>
    </center>

    <div class="container" style="border-radius: 20px;padding: 25px;">


        <table class="table table-striped" style="color: white;font-size:20px;">
            <thead class="thead-light">
            <tr>
                <th scope="col">Todo</th>
                <th scope="col">deadline</th>
                <th scope="col" align="center"></th>
            </tr>
            </thead>
            <tbody>
            {% for todo in all_todo %}

                <tr style="background-color:white;">
                    {% if todo.done == False %}
                        <th  scope="row" style="font-weight: 600">
                            <i class="fa fa-circle" style="color: red"></i>&nbsp;<span style="color: black">{{ todo.title }}</span></th>
                    {% elif todo.done %}
                        <th scope="row"style="font-weight: 600">
                            <i class="fa fa-circle" style="color: green"></i>&nbsp;<span style="color: black">{{ todo.title }}</span></th>
                    {% endif %}
                    <td ><span style="color: black">{{ todo.due_date }}</span></td>
                    {% if todo.done == False %}

                        <td align="center"><a class="btn btn-primary" href="{% url 'assignments:update_todo' todo.id %}" role="button">
                            <i class="fa fa-edit"></i>
                            Done</a></td>
                    {% elif todo.done%}
                        <td align="center"><a class="btn btn-primary" href="{% url 'assignments:delete_todo' todo.id %}" role="button">
                            <i class="fa fa-trash"></i>delete</a></td>
                    {% endif %}


                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

{% endblock %}