complete/accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

#app_name='accounts'

urlpatterns=[
        path('index/',views.index, name='index'),
        path('',views.home,name='home'),
        path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'), #login url
        path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),  #logout url
        path('register/',views.register,name='register'),             #register url
        path('register/company',views.registercompany,name='registercompany'),             #register url
        path('profile/',views.view_profile,name='view_profile'),
        path('profile/edit/',views.edit_profile,name='edit_profile'),
        path('profile/password/',views.change_password,name='change_password'),
        path('change-password/',views.change_password,name='change_password'), #change password url
        path('recent_activities/',views.list_activities,name='list_activities'),
        path('employee_activity/<int:pk>/',views.specific_activities,name='specific_activities'),
        path('inter_reg/',views.inter_reg,name='inter_reg'),

        path('reset-password/',auth_views.PasswordResetView.as_view(template_name='accounts/reset_password.html'
        ,email_template_name = 'accounts/reset_password_email.html'),name='password_reset'), # password reset url
        # password reset done url
        path('reset-password/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'),
        name='password_reset_done'),
        #password reset confirm url
        path('reset-password/confirm/(<uidb64>[0-9A-Za-z]+)-(<token>.+)/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html'),
        name='password_reset_confirm'),
        #password reset complete url
        path('reset-password/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'),name='password_reset_complete'),
        #path('reset/real', include('django.contrib.auth.urls')),

        url(r'^profile/(?P<pk>\d+)/$',views.view_profile,name='view_profile_with_pk'),

        path('createteam/',views.create_team,name='reg_team'),
        path('addusertoteam/',views.add_user_team,name='add_user_team'),
        path('todolists/<int:pk>/',views.todo,name='accounts.todo'),
        path('group/<int:pk>/',views.view_group_with_pk,name='view_group_with_pk'),
        path('uploadfilepath/<int:pk>/',views.fileupload,name='file_upload'),
        path('filedownload/<int:pk>/',views.filedownload,name='file_download'),


]

complete/blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

#app_name='blog'
urlpatterns = [
    path('show/<int:pk>/', views.index, name='blog_index'),
    #url(r'^show/(?P<pk>\d+)/$',views.index,name='blog_index'),
    path('post/<int:pk>/', views.details, name='details'),
    path('post/new/<int:pk>/', views.newpost, name='newpost'),
    path('post/<int:pk>/edit', views.editpost, name='editpost'),
    path('post/<int:pk>/delete', views.deletepost, name='deletepost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.addcomment, name='add-comment'),
]

complete/complete/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from accounts.views import home
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from chat.views import index

from put_calendar.api.router import router

from put_calendar.views import *


from rest_framework.authtoken import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('assignments/', include('assignments.urls')),
    url('notifications/', include('notifications.urls')),
    url('clients/', include('clients.urls')),
    url('accounts/',include('accounts.urls')),
    url('history/', include('history.urls')),
    url('^$',home),
    url('blog/', include('blog.urls')),
    url('calendar/',include('put_calendar.urls')),
    url('chat/',include('chat.urls')),
    url('api/posts/',include('blog.api.urls')),
    path('api/',include(router.urls)),
    path('api-token-auth/',views.obtain_auth_token,name='api-token-auth'),


    url(r'^api/dates/$', DatesListView.as_view()),
    url(r'^api/dates/(?P<pk>\d+)/$', DatesView.as_view()),
    url(r'^api/user/$', UserListView.as_view()),
    url(r'^api/user/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^api/filter/(?P<pk>\d+)/$', DatesFilterView.as_view()),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complete/accounts/models.py
from __future__ import print_function
from googleapiclient.discovery import build
from httplib2 import Http
import httplib2
from oauth2client import file, client, tools
from apiclient.http import MediaFileUpload, MediaIoBaseDownload
from apiclient import discovery
import os,io
from django.dispatch import receiver
from django.db.models.signals import post_save



# If modifying these scopes, delete the file token.json.
SCOPES = 'https://www.googleapis.com/auth/drive'


##google drive api modules



from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.contrib.auth.models import User


CHOICES = (
    ('CEO','CEO'),
    ('Project Manager', 'Project Manager'),
    ('Employee','Employee'),
)

# Create your models here.{Database Table models}

class Company(models.Model): #[Table of companies ]
    company_name=models.CharField(max_length=100,default='',primary_key=True)

    def __str__(self):
        return self.company_name


class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.PROTECT) #or models.CASCADE
    Jobtitle=models.CharField(max_length=100,default='',choices=CHOICES)
    city=models.CharField(max_length=100,default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='image_profile',blank=True)
    company_name=models.ForeignKey(Company,default='',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class teamtable(models.Model):

    company_name=models.ForeignKey(Company,default='',on_delete=models.CASCADE)
    group_name=models.CharField(max_length=100,default='')

    class Meta:
        unique_together = (('company_name', 'group_name'),)
    def __str__(self):
        return self.group_name



class GroupUserTable(models.Model):
    team_details=models.ForeignKey(teamtable,default='',on_delete=models.CASCADE)
    user_name=models.ForeignKey(User,default='',on_delete=models.CASCADE)
    class Meta:
        unique_together = (('team_details', 'user_name'),)
    def __str__(self):
        return str(self.team_details)


class Todolist(models.Model):
    status=models.BooleanField(default=False)
    title=models.CharField(max_length=250)
    project_name=models.CharField(max_length=250)

    description=models.CharField(max_length=100,default='')
    deadline=models.DateField(default=timezone.now)
    assigned=models.DateField(default=timezone.now)
    team_details=models.ForeignKey(teamtable,default='',on_delete=models.CASCADE)
    user_name=models.ForeignKey(User,default='',on_delete=models.CASCADE)

    class Meta:
        unique_together = (('title', 'user_name'),)

    def __str__(self):
        return self.title

class work_assigned(models.Model):
    work=models.ForeignKey(Todolist,default='',on_delete=models.CASCADE)
    user_assign=models.ForeignKey(User,default='',on_delete=models.CASCADE)
    def __str__(self):
        return self.work.title
class to_notify(models.Model):
    work=models.ForeignKey(Todolist,default='',on_delete=models.CASCADE)
    done=models.BooleanField(default=False)
    user_notify=models.ForeignKey(User,default='',on_delete=models.CASCADE)



class upload_file(models.Model):
    upload=models.FileField(upload_to='files')


class foldertable(models.Model):

    folderid=models.CharField(max_length=100,default='')
    foldername=models.CharField(max_length=100,default='')
    team_details=models.ForeignKey(teamtable,default='',on_delete=models.CASCADE)

    

    def __str__(self):
        return self.foldername




class filetable(models.Model):

    parentfolder=models.ForeignKey(foldertable,default='',on_delete=models.CASCADE)
    fileid=models.CharField(max_length=100,default='')
    filename=models.CharField(max_length=100,default='')



@receiver(post_save,sender=teamtable)
def createfolder(sender,instance,created,**kwargs):
    cwd = os.getcwd()

    token=str(cwd)+'/accounts/token.json'
    credit=str(cwd)+'/accounts/credentials.json'

    if created:
        store = file.Storage(token)
    creds = store.get()
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets(credit, SCOPES)
        creds = tools.run_flow(flow, store)
    service = build('drive', 'v3', http=creds.authorize(Http()))

    foldername=str(instance.group_name)+'-->'+str(instance.company_name)

    file_metadata = {
    'name': foldername,
    'mimeType': 'application/vnd.google-apps.folder'
    }
    file1 = service.files().create(body=file_metadata,
                                    fields='id').execute()

    print ('Folder ID: %s' % file1.get('id'))

    folderid=file1.get('id')

    foldertable.objects.create(
                                folderid=folderid,
                                foldername = foldername,
                                team_details = instance

                                )

complete/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.forms import User
from .models import UserProfile,Company,teamtable,GroupUserTable,Todolist,work_assigned,to_notify,upload_file

class RegistrationForm(UserCreationForm):      #Our own custom RegistrationForm
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self,commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']
        #user.company_name=self.cleaned_data['company_name']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):  #our own custom edit profile form
    class Meta:
        model=User
        fields=(
            'email',
            'first_name',
            'last_name',
            'password',
        )
class ChangeProfileForm(forms.ModelForm):  #our own custom edit profile form
    class Meta:
        model=UserProfile
        fields=(
            'phone',
            'city',
        )

class customreg(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=(
            'Jobtitle',
            'city',
            'phone',
            'company_name',
        )

class customregcompany(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=(
            'Jobtitle',
            'city',
            'phone',
        )

class regcompany(forms.ModelForm):
    class Meta:
        model=Company
        fields=(
            'company_name',
        )
class regteam(forms.ModelForm):

    class Meta:
        model=teamtable
        fields=(
            'group_name',
        )
class adduserform(forms.ModelForm):
    class Meta:
        model=GroupUserTable
        fields=(
            'user_name',
        )

class todoform(forms.ModelForm):
    class Meta:
        model=Todolist
        fields=(
            'title',
            'project_name',
            'description',
            'deadline',
        )
class assign_work(forms.ModelForm):
    class Meta:
        model=work_assigned
        fields=(
            'user_assign',
        )
class notify_work(forms.ModelForm):
    class Meta:
        model=to_notify
        fields=(
            'user_notify',
        )

class uploadfileform(forms.ModelForm):
    class Meta:
        model=upload_file
        fields=(
            'upload',
        )

complete/accounts/templates/accounts/create_team.html
{% extends 'base.html' %}
  {% block head %}
  <title>Create Team </title>
  {% endblock %}

  {% block body %}
  <div class="container">
    <h1>Welcome</h1>
    <p>
      you can create team here
    </p>
    <h2> Create team  </h2>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Create Group</button>
    </form>
  </div>
  {% endblock %}

complete/accounts/templates/accounts/edit_profile.html
{% extends 'homepage.html' %}

{% block head %}
    <title>EDIT PROFILE PAGE</title>
    <style>
        .form-control {
            width: 40%;
        }
    </style>>
{% endblock %}

{% block content %}
    <script type="text/javascript">
        $(function () {

            $("#id_email").addClass("form-control");
            $("#id_first_name").addClass("form-control");
            $("#id_last_name").addClass("form-control");
            $("#id_phone").addClass("form-control");
            $("#id_city").addClass("form-control");
        });
    </script>
    <br><br>
    <div class="card">
        <div class="card-body">
            <h1 class="display-4" style="font-size:35px;font-weight:400;">Edit Profile:</h1><br>
            <div class="container" style="width:50%;">
                <form method="post">
                    {% csrf_token %}
                    First name: {{ form.first_name }}
                    Last name: {{ form.last_name }}
                    Email: {{ form.email }}
                    <br>
                    Phone: {{ form1.phone }}
                    City: {{ form1.city }}
                    <button type="submit">Submit</button>

                </form>
                <br>
                <a class="nav-link" href='/accounts/change-password'>
                    <button type="button" class="btn btn-danger">Change password</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

complete/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
  {% block head %}

  <title>Home</title>
  <style>
    a:hover, a = {
      text-decoration=none;
    }
    </style>
  {% endblock %}

  {% block body %}
  <br><br><br>


  <!-- The Modal -->
  <div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title"> Create team here  </h4>
          <button type="button" class="btn btn-danger" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="container">
            <form method="post">
              {% csrf_token %}
              {{form.as_p}}
              <button type="submit">Create team</button>
            </form>
          </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>

  </div>

  <div class="container" style="color:white;font-size:25px;">
    <br>
    <br>
    {{message}}
    <br>
    <br>
  </div>
  <div class="container">
      <div class="row">
          <div class="col-lg-3">
              <div class="display-3" style="color:white;">
                  Teams
              </div>
          </div>
          <div class="col-lg-3" style="margin-top:auto;">

                  <button class="btn btn-info" data-toggle="modal" data-target="#myModal"
                          style="background-color:teal;">
                      Create team <span class="fa fa-plus-circle"></span></button>

          </div>
          <div class="col-lg-3" style="margin-top:auto;">
            <a href="{% url 'list_activities' %}">
                <button class="btn btn-info"
                        style="background-color:teal;margin-top:10px;">
                    Recent activities
                </button>
            </a>
          </div>
          
      </div>
      <hr style="border-color:darkgray;">


    <div class="row">

    {% for eachgrp in groups %}
    <div class="col-lg-3" style="padding: 5px;">
        <div class="text-center">
            <image src="{% static 'images/team.png' %}"
                   style="height:auto;width:45%;alignment: center;"></image>
            <br><br>
            <a href="{% url 'view_group_with_pk' pk=eachgrp.team_details.pk %}"
               style="text-decoration:none;">
                <button type="button" class="btn btn-primary"
                        style="background-color: teal;color:white;">{{ eachgrp.team_details }}</button>
            </a>
        </div>
    </div>



    {% endfor %}

    </div>

  </div>
  {% endblock %}

complete/accounts/templates/accounts/login.html
{% extends 'base.html' %}

  {% block head %}
    <style>
    #grad{
        background-image: linear-gradient(to bottom left, #ffb2c4f2, #85d8fed1);
    }
    a,a:hover{
        color:#005abb;
        text-decoration: none;
    }
    .md-form{
        font-size: 20px;
        color: #383838;
    }
    </style>

  <title>Login Page</title>
  {% endblock %}

  {% block body %}


  <script type="text/javascript">
    $(function(){

        $("#id_username").addClass("form-control");
        $("#id_password").addClass("form-control");
});
  </script>
  <br><br><br>
  <div class="card" style="margin-left: 55px;border-radius: 15px;width: 500px;height: 520px;">

    <h5 class="card-header info-color white-text text-center py-4">
      <strong class="display-4" style="font-size:40px;">Log in</strong>
    </h5>
    <!--Card content-->
    <div class="card-body px-lg-5 pt-0" id="grad" style="border-radius: 11px;">
    <br><br>
      <!-- Form -->
      <form class="text-center" method="post" autocomplete="on">

        {% csrf_token %}
        <!-- Email -->
        <div class="md-form" style="font-size: 20px;">
          <label for="materialLoginFormEmail">username</label>
          {{form.username}}
        </div>
          <br>
        <!-- Password -->
        <div class="md-form" style="font-size: 20px;">
          <label for="materialLoginFormPassword">Password</label>
          {{form.password}}

        </div>

        <div class="d-flex justify-content-around">
          <div>
            <!-- Remember me -->
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="materialLoginFormRemember">
              <label class="form-check-label" for="materialLoginFormRemember">Remember me</label>
            </div>
          </div>
          <div>
            <!-- Forgot password -->
            <a href="/accounts/reset-password">Forgot password?</a>
          </div>
        </div>
        <br>
        <!-- Sign in button -->
        <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">Sign in</button>

        <!-- Register -->
        <p>Not a member?
          <a href="/accounts/inter_reg/">Register</a>
        </p>

      </form>
      <!-- Form -->

    </div>

  </div>
    {% endblock %}
  <!-- Material form login -->

complete/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
    <title>LOGOUT PAGE</title>
{% endblock %}

{% block body %}
    <br><br><br>
    <div class="card" style="width: 70%;margin-left:15%;">

        <div class="card-body">
            <div class="text-center">
                <div class="display-4">Successfully logged out.</div>
                <br><br>
                <a href='/accounts/login'>
                    <button type="button" class="btn btn-primary">Click here to log in</button>
                </a>
                <br><br>
            </div>
        </div>
    </div>
{% endblock %}

complete/accounts/templates/accounts/profile.html
{% extends 'homepage.html' %}
{% load crispy_forms_tags %}


{% block head %}
  <title>USER PROFILE PAGE</title>
{% endblock %}

{% block content %}

<div class="card">
<div class="card-body">
 <div class="container " id="f4">
   <div class="row">
    <div class="col-md-6">
      <h1 class="display-4" style="font-size:35px;font-weight:400;"> User Profile</h1><br>
      <p> Username : {{user}} </p>
      <p> First Name: {{user.first_name}} </p>
      <p> Last Name: {{user.last_name}} </p>
      <p> Email: {{user.email}} </p>
      <p> Jobtitle: {{user.userprofile.Jobtitle}} </p>
      <p> Phone: {{user.userprofile.phone}} </p>
      <p> Company: {{user.userprofile.company_name}} </p>
      <p> City: {{user.userprofile.city}} </p>
    </div>
    <div class="col-md-5"  >

    <!--    {% if user.userprofile.image %}
          <img src="{{user.userprofile.images.url}}" alt="profile-pic" style="width:200px;border-radius:50%">

        {% else %}


        <p >

          <br><br><br><br><br>&nbsp;&nbsp;&nbsp;
          <img src="../../static/accounts/images/profile.png"  style="width:200px;border-radius:50%">
        </p>
        {% endif %}  -->
        {% if user.userprofile.image  %}
    <img src="{{user.userprofile.image.url}}" alt="profile-pic" width="240" style="width:200px;border-radius:50%">
      {{user.userprofile.image.path}}
    {% else %}
    <img src="../../static/accounts/images/profile.png"  style="width:200px;border-radius:50%">
    {% endif %}
  </div>

    </div>
    </div>
 </div>
 </div>
 </div>

{% endblock content %}

complete/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
  <title>REGISTER</title>
    <style>
    #grad{
        background-image: linear-gradient(to top left, #feffa1f2, #fe8585);
    }
    a,a:hover{
        color:#005abb;
        text-decoration: none;
    }
    .md-form{
        font-size: 20px;
        color: #383838;
    }
    </style>
{% endblock %}

{% block body %}
<br><br><br><br>

<script type="text/javascript">
        $(function () {

            $("#id_username").addClass("form-control");
            $("#id_first_name").addClass("form-control");
            $("#id_last_name").addClass("form-control");
            $("#id_password1").addClass("form-control");
            $("#id_password2").addClass("form-control");
            $("#id_email").addClass("form-control");
            $("#id_Jobtitle").addClass("form-control");
            $("#id_city").addClass("form-control");
            $("#id_phone").addClass("form-control");
            $("#id_company_name").addClass("form-control");
        });
    </script>


<div class="row">
    <div class="col-lg-8">
    <!--Card content-->
    <div class="card" style="width:580px;margin-left:50px">

        <h5 class="card-header info-color white-text text-center py-4">
            <strong class="display-4" style="font-size:39px;">Employee registration</strong>
        </h5>

        <!--Card content-->
        <div class="card-body px-lg-5 pt-0" id="grad">
            <br>
            <!-- Form -->
            <form method="post" action="/accounts/register/" class="text-center" style="color: #383838;">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col">
                        <div class="md-form">
                            <label for="materialRegisterFormFirstName">username</label>
                            {{ form1.username }}<br>

                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <!-- First name -->
                        <div class="md-form">
                            <label for="materialRegisterFormFirstName">First name</label>
                            {{ form1.first_name }}<br>

                        </div>
                    </div>
                    <div class="col">
                        <!-- Last name -->
                        <div class="md-form">
                            <label for="materialRegisterFormLastName">Last name</label>
                            {{ form1.last_name }}<br>


                        </div>
                    </div>
                </div>

                <!-- E-mail -->
                <div class="form-row">
                    <div class="col">
                        <div class="md-form mt-0">
                            <label for="materialRegisterFormEmail">E-mail</label>
                            {{ form1.email }}<br>


                        </div>
                    </div>
                    <div class="col">
                        <div class="md-form">
                            <label for="materialRegisterFormPassword">Password</label>
                            {{ form1.password1 }}<br>


                            <small id="materialRegisterFormPasswordHelpBlock" class="form-text text-muted mb-4">
                                At least 8 characters and 1 digit
                            </small>
                        </div>
                    </div>
                </div>

                <div class="md-form">
                    <label for="materialRegisterFormPassword">Repeat password</label>
                    {{ form1.password2 }}<br>


                </div>

                <div class="form-row">
                    <div class="col">
                        <div class="md-form">
                            <label for="materialRegisterFormPhone">jobtitle</label>
                            {{ form.Jobtitle }}<br>


                        </div>
                    </div>
                    <div class="col">
                        <div class="md-form">
                            <label for="materialRegisterFormPhone">Company name</label>
                            {{ form.company_name }}<br>



                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <div class="md-form">
                            <label for="materialRegisterFormPhone">City</label>
                            {{ form.city }}<br>

                        </div>
                    </div>
                    <div class="col">
                        <div class="md-form">
                            <label for="materialRegisterFormPhone">Phone number</label>

                            {{ form.phone }}<br>

                        </div>
                    </div>
                </div>


                <!-- Sign up button -->
                <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">
                    Register
                </button>
            </form>
        </div>
    </div>
    </div>
    <div class="col-lg-3">
        <image src="{% static 'images/flatface.png' %}" style="height:auto;width:inherit;alignment: left;"></image>
    </div>
    </div>
    <!-- Material form register -->
{% endblock %}

complete/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
  {% block head %}
  <title>Login Page</title>
  {% endblock %}

  {% block body %}
      <br><br>
      <div class="text-center">
  <div class="card">
      <div class="card-body">
    <p class="display-4">Password Reset</p>
    <p> Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one. </p>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Reset Password</button>
    </form>
  </div>
  </div>
      </div>
  {% endblock %}

complete/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}
  {% block head %}
  <title>Login Page</title>
  {% endblock %}

  {% block body %}
  <div class="card">
    <div class="card-body">
    <h1>Enter new Password </h1>
    <p> Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one. </p>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Reset Password</button>
    </form>
    </div>
  </div>
  {% endblock %}

complete/accounts/templates/accounts/todolist.html
{% extends 'base.html' %}
{% block head %}
    <title>Create Team </title>
{% endblock %}

{% block body %}
    <script type="text/javascript">
        $(function () {

            $("#id_title").addClass("form-control");
            $("#id_deadline").addClass("form-control");
            $("#id_project_name").addClass("form-control");
            $("#id_description").addClass("form-control");
            $("#id_user_assign").addClass("form-control");
            $("#id_user_notify").addClass("form-control");
        });
    </script>

    <br><br><br>

    <div class="row">
        <div class="col-lg-6">
            <div class="card" style="width:580px;margin-left:25px;">
                <div class="card-body">
                    <h2 class="display-4">To do </h2>
                    <form method="post">
                        {% csrf_token %}
                        Title: {{ form.title }}<br>
                        Project name: {{ form.project_name }}<br>
                        Description: {{ form.description }}<br>
                        <div class="row">
                            <div class="col-lg-3">

                        {{ form1.as_p }}
                            </div>
                            <div class="col-lg-3">
                        {{ form2.as_p }}
                                </div>
                            <div class="col-lg-3">
                                Deadline: {{ form.deadline }}
                            </div>
                        </div>
                        <br>
                            <button type="submit" class="btn btn-danger" style="background-color: #d2324b;">Add a to do</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                <p class="text-center">
                    <h3 class="display-4" style="font-size: 30px;font-weight:400;">Lists of Things to do</h3>
                </p>
                <hr style="border-color: #8b8e94">

                    {% for list in alllist %}
                        <p><span style="font-size: 19px;">{{ list.title }}</span></p>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}