complete/assignments/urls.py
from django.conf.urls import url
from . import views

app_name = 'assignments'




urlpatterns = [
    #assignments


    #assignments/display
    url('display/$',views.display_view, name='display'),

    #assignments/my_todo
    url('my_todo/$',views.my_todo_view, name='my_todo'),

    #assignments/display/delete
    url('display/delete/(?P<task_id>[0-9]+)',views.delete_tasks,name='delete_task'),

    # assignments/display/update
    url('display/update/(?P<task_id>[0-9]+)', views.update_tasks, name='update_task'),

    #assignments/my_todo/add
    url('my_todo/add/', views.add_todo_list_view, name='add_todo'),

    url('my_todo/delete/(?P<todo_id>[0-9]+)', views.delete_todo, name='delete_todo'),

    url('my_todo/update/(?P<todo_id>[0-9]+)', views.update_todo, name='update_todo'),

]

complete/blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

#app_name='blog'
urlpatterns = [
    path('show/<int:pk>/', views.index, name='blog_index'),
    #url(r'^show/(?P<pk>\d+)/$',views.index,name='blog_index'),
    path('post/<int:pk>/', views.details, name='details'),
    path('post/new/<int:pk>/', views.newpost, name='newpost'),
    path('post/<int:pk>/edit', views.editpost, name='editpost'),
    path('post/<int:pk>/delete', views.deletepost, name='deletepost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.addcomment, name='add-comment'),
]

complete/clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'clients'

urlpatterns = [
    #clients
    url('^$', views.index, name='index'),

    #clients/create/
    url('create/', views.client_create_view,name='create')
]

complete/complete/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from accounts.views import home
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from chat.views import index

from put_calendar.api.router import router

from put_calendar.views import *


from rest_framework.authtoken import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('assignments/', include('assignments.urls')),
    url('notifications/', include('notifications.urls')),
    url('clients/', include('clients.urls')),
    url('accounts/',include('accounts.urls')),
    url('history/', include('history.urls')),
    url('^$',home),
    url('blog/', include('blog.urls')),
    url('calendar/',include('put_calendar.urls')),
    url('chat/',include('chat.urls')),
    url('api/posts/',include('blog.api.urls')),
    path('api/',include(router.urls)),
    path('api-token-auth/',views.obtain_auth_token,name='api-token-auth'),


    url(r'^api/dates/$', DatesListView.as_view()),
    url(r'^api/dates/(?P<pk>\d+)/$', DatesView.as_view()),
    url(r'^api/user/$', UserListView.as_view()),
    url(r'^api/user/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^api/filter/(?P<pk>\d+)/$', DatesFilterView.as_view()),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complete/history/urls.py
from django.conf.urls import url
from history import views
from django.urls import path

app_name = 'history'

urlpatterns = [
 url('activity/',views.trials,name = 'trials'),
]

complete/put_calendar/urls.py
from django.urls import path
from put_calendar import views
from django.conf.urls import url
app_name='put_calendar'
urlpatterns = [






    url(r'^next/(?P<select>\w+)/(?P<show>\w+)/$', views.date, name='date'),
    #path('next/<select>/',views.date,name = "date"),
    #path('back/<select>/',views.date1,name = "date1"),
    url(r'^back/(?P<select>\w+)/(?P<show>\w+)/$', views.date1, name='date1'),
    path('events_enter/<int:date_selected>',views.event_enter,name="event_enter"),
    url(r'^land/(?P<select>\w+)/(?P<show>\w+)/$', views.hello, name='index'),
	url(r'^choose/(?P<select>\w+)/(?P<show>\w+)/$', views.choose_event, name='choose'),


]

complete/templates/base1.html
<!DOCTYPE html>
<html>
  <head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">

    {% load static %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'accounts\styles.css' %}" type ="text/css">
    <meta name='viewport' content="width=device-width,initial-scale=1.0 ">
    {% block head %}
    <title></title>
    {% endblock %}
  </head>
  <body>
    <br>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Kick Start</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
              <li><a class="nav-link" href="/accounts/">Home</a></li>

              <li><a class="nav-link" href='/accounts/profile'>View Profile</a></li>
              <li><a class="nav-link" href='/accounts/profile/edit'>Edit Profile</a></li>
              <li><a class="nav-link" href='/accounts/change-password'>Change Password</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li><a class="nav-link" href='/accounts/logout'>Logout</a></li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
              <li><a class="nav-link" href='/accounts/reset-password'>Reset Password</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li><a class="nav-link" href='/accounts/login'>Login</a></li>
              <li><a class="nav-link" href="/accounts/register">Register</a></li>
              <li><a class="nav-link" href="/accounts/register/company">Register Your Company </a></li>
            </ul>
            {% endif %}
        </div>

      </nav>
      {% block body %}
      This is base for you
      {% endblock %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>

</html>

complete/templates/baseChat.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "css/style1.css" %}" type="text/css" media="screen" />
	<script src="{% static "js/jquery-1.12.2.min.js" %}" type="text/javascript"></script>
	<script src="{% static "js/reconnecting-websocket.min.js" %}" type="text/javascript"></script>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'accounts\styles.css' %}" type ="text/css">
  <meta name='viewport' content="width=device-width,initial-scale=1.0 ">
	{% block extra_head %}{% endblock %}
</head>
<body  style="background-image:url('{% static 'images/13390.jpg' %}');background-size:cover; background-repeat:no-repeat;">
  <br>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="navbar-header">
    <a class="navbar-brand" href="/">Kickstart</a>
  </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
              <li><a class="nav-link" href="/accounts/">Home <span class="fa fa-home"></span></a></li>
          </ul>
          <ul class="navbar-nav ml-auto">
          <li><a class="nav-link" href='/accounts/profile'>Profile <span class="fa fa-user"></span></a></li>

            <li><a class="nav-link" href='/accounts/logout'>Logout <span class="fa fa-sign-out-alt"></span></a></li>
          </ul>
          {% else %}
          <ul class="navbar-nav mr-auto">
              <li><a class="nav-link" href="/accounts/index">Home <span class="fa fa-home"></span></a></li>
          </ul>
                      <ul class="navbar-nav ml-auto">
              <li><a class="nav-link" href='/accounts/login'>Login <span class="fa fa-sign-in-alt"></span></a></li>
            <li><a class="nav-link" href="/accounts/inter_reg">Register <span class="fa fa-user-plus"></span></a></li>
          </ul>
          {% endif %}
      </div>

    </nav>
<br><br>
	<section style="background-color: white">
		{% block content %}
		{% endblock %}
	</section>
	{% block extra_body %}{% endblock %}
</body>
</html>

complete/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>dashboard</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body style="background-image:url('{% static 'images/13390.jpg' %}');background-size:cover; background-repeat:no-repeat;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="navbar-header">
      <a class="navbar-brand" href="/">Kickstart</a>
    </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li><a class="nav-link" href="/accounts/">Home <span class="fa fa-home"></span></a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
            <li><a class="nav-link" href='/accounts/profile'>Profile <span class="fa fa-user"></span></a></li>

              <li><a class="nav-link" href='/accounts/logout'>Logout <span class="fa fa-sign-out-alt"></span></a></li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
              <li><a class="nav-link" href='/accounts/reset-password'>Reset Password</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li><a class="nav-link" href='/accounts/login'>Login <span class="fa fa-sign-in-alt"></span></a></li>
              <li><a class="nav-link" href="/accounts/inter_reg">Register <span class="fa fa-sign-in-alt"></span></a></li>
            </ul>
            {% endif %}
        </div>

      </nav>

<br><br><br>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>{{ request.user }}</h3>
            </div>

            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fa fa-user"></i>
                        My Profile
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'view_profile' %}">View Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'edit_profile' %}">Edit Profile</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'history:trials' %}">
                        <i class="fas fa-briefcase"></i>
                        My Recent Activity
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        My Task and Assignments
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'assignments:display' %}">My Assignments</a>
                        </li>
                        <li>
                            <a href="{% url 'assignments:my_todo' %}">self assigned tasks</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'notifications:index' %}">
                        <i class="fas fa-bell"></i>
                        Notifications
                    </a>
                </li>
                <li>
                    <a href="{% url 'put_calendar:index' select='1' show='1' %}">
                        <i class="fas fa-calendar"></i>
                        calendar
                    </a>
                </li>
                <li>
                    <a href="{% url 'clients:index' %}">
                        <i class="fas fa-address-book"></i>
                        Client List
                    </a>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>


                </div>
                            <h2 class="display-4" style="font-size:50px;">Personal Dashboard</h2>

            </nav>


{% block content %}
{% endblock content %}
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>


    {% block content1 %}

{% endblock content1 %}

</body>
</html>

complete/templates/index.html
{% extends "baseChat.html" %}

{% block title %}GroupChat{% endblock %}
{% block header_text %}GroupChat{% endblock %}

{% block content %}
  <br>
    <div id="chats">
    </div>

{% endblock %}


{% block extra_body %}

    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);
            var socket = new ReconnectingWebSocket(ws_path);

            // Handle incoming messages
            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input style='width:70%;'><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";


                            // Message
                            var position ='left'
                            if(data.me==1) position='right';
                            console.log(data.me);
                            ok_msg = "<div class='box' align="+position+">"+
                                    "<div style='max-width:80%;' class='container' >" +
                                    "<div class='username'>" + data.username + "</div>" +
                                    "<p class='body'>" + data.message + "</p>" +
                                    "</div>"+
                                    "</div>";

                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            function initial() {
                var k;
                {% for room in rooms%}
                k={{room.id}};
                {% endfor %}
                roomId = k.toString();

                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));

            };

            socket.onopen = function () {
                console.log("Connected to chat socket");
                initial();
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
{% endblock %}

complete/templates/testhome.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "css/index.css" %}">

</head>
<body>

<!-- navbar-->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <div class="navbar-header">
            <li class="nav-item active">
                <a class="nav-link" href="#">Kickstart</a>
            </li>
                </div>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
            </li>
        </ul>
    </div>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item" style="padding-top: 8px;">
                <a class="nav-link" href="#">Register your company</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sign up<span class="fa fa-user-o" style="font-size: 16px;"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Login<span class="fa fa-sign-in" style="font-size: 16px;"></span></a>
            </li>
        </ul>
    </div>
</nav>

<!--header-->

<div class="jumbotron jumbotron-fluid" style="padding-top: 110px;">
        <h1 class="text-center">Welcome to Kickstart!</h1>
        <p class="text-center">
            <small>Manage workflow, assign tasks, complete work efficiently!</small>
        <p>
</div>

<!--random stuff related to service-->
<div class="row">

    <div id="section1" class="col-lg-8">
        <h1 class="page-header">Explain how our service works</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut dui dui.
            Praesent quis orci sagittis tellus commodo ultrices a at ante. Praesent viverra ipsum id massa porttitor,
            sed euismod ante blandit.
            Nullam vel vehicula sem, sit amet laoreet justo. Ut vitae quam purus. In sodales libero ligula. Sed aliquet
            nisl odio.
            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Pellentesque non magna non est suscipit fermentum. Fusce risus nisi, dignissim in tincidunt vel, mattis nec
            arcu.
        </p>
    </div>

    <div class="col-lg-4">
        <h1>Images?</h1>
    </div>

</div>

<div class="row">

    <div class="col-lg-4">
        <h1>Images?</h1>
    </div>

    <div id="section2" class="col-lg-8">
        <h1 class="page-header">Feature 1</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut dui dui.
            Praesent quis orci sagittis tellus commodo ultrices a at ante. Praesent viverra ipsum id massa porttitor,
            sed euismod ante blandit.
            Nullam vel vehicula sem, sit amet laoreet justo. Ut vitae quam purus. In sodales libero ligula. Sed aliquet
            nisl odio.
            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Pellentesque non magna non est suscipit fermentum. Fusce risus nisi, dignissim in tincidunt vel, mattis nec
            arcu.
        </p>
    </div>
</div>

<div class="row">

    <div id="section3" class="col-lg-8">
        <h1 class="page-header">Feature 2</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut dui dui.
            Praesent quis orci sagittis tellus commodo ultrices a at ante. Praesent viverra ipsum id massa porttitor,
            sed euismod ante blandit.
            Nullam vel vehicula sem, sit amet laoreet justo. Ut vitae quam purus. In sodales libero ligula. Sed aliquet
            nisl odio.
            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Pellentesque non magna non est suscipit fermentum. Fusce risus nisi, dignissim in tincidunt vel, mattis nec
            arcu.
        </p>
    </div>

    <div class="col-lg-4">
        <h1>Images?</h1>
    </div>
</div>

<div class="row">

    <div class="col-lg-4">
        <h1>Images?</h1>
    </div>

    <div id="section4" class="col-lg-8">
        <h1 class="page-header">Feature 3</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut dui dui.
            Praesent quis orci sagittis tellus commodo ultrices a at ante. Praesent viverra ipsum id massa porttitor,
            sed euismod ante blandit.
            Nullam vel vehicula sem, sit amet laoreet justo. Ut vitae quam purus. In sodales libero ligula. Sed aliquet
            nisl odio.
            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Pellentesque non magna non est suscipit fermentum. Fusce risus nisi, dignissim in tincidunt vel, mattis nec
            arcu.
        </p>
    </div>
</div>

<!--footer-->
<div class="container-fluid" style="background-color:tomato;">
    <div class="row">
        <div class="col-lg-6">
            <h2>About</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Duis nec enim rhoncus, sodales libero a, tincidunt dui.
                Suspendisse sodales elementum consectetur. Suspendisse potenti.
                Nullam lobortis tellus id quam scelerisque sodales. Integer auctor ut odio at varius.
                Nunc iaculis elementum justo, eu elemenetum augue blandit quis.
                Vivamus pellentesque felis in lectus ultricies, sed iaculis magna ullamcorper.
                Aliquam felis lacus, feugiat in ultricies sit amet, tempus nec mauris.
                Aenean fringilla massa ultricies tincidunt commodo. Aliquam erat volutpat.
            </p>
        </div>
        <div class="col-lg-6">
            <h2>Contacts</h2>
            <ul style="padding-left:inherit;">
                <li class="list-group-item">email-1</li>
                <li class="list-group-item">email-2</li>
                <li class="list-group-item">email-3</li>
            </ul>
        </div>
    </div>
</div>

<!-- social media-->
<div class="container-fluid" style="background-color:#000000e6;padding-bottom:12px;">

    <h3 class="text-center">
        <small style="color:darkgray;">Follow us at:</small>
    </h3>

    <div class="text-center">
        <a class="fa fa-twitter" href="#"></a>
        <a class="fa fa-facebook-square" href="#"></a>
        <a class="fa fa-instagram" href="#"></a>
        <a class="fa fa-google-plus-official" href="#"></a>
    </div>
</div>

</body>
</html>